# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MonaLisaui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 1121, 641))
        self.bg.setStyleSheet("background-color: rgb(243, 252, 255);\n"
"border: 5px Solid Pink\n"
"")
        self.bg.setText("")
        self.bg.setScaledContents(True)
        self.bg.setObjectName("bg")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(780, 570, 241, 61))
        self.close_button.setStyleSheet("color: rgb(255, 193, 254);\n"
"background-color: rgb(219, 255, 253);\n"
"font: 75 26pt \"MS Shell Dlg 2\";")
        self.close_button.setObjectName("close_button")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(780, 500, 241, 61))
        self.start_button.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";\n"
"color: rgb(216, 249, 255);")
        self.start_button.setObjectName("start_button")
        self.frontier = QtWidgets.QLabel(self.centralwidget)
        self.frontier.setGeometry(QtCore.QRect(710, 10, 391, 411))
        self.frontier.setStyleSheet("border: 2px Solid Pink\n"
"")
        self.frontier.setText("")
        self.frontier.setPixmap(QtGui.QPixmap(".\\../../../Downloads/avatar.png"))
        self.frontier.setObjectName("frontier")
        self.time = QtWidgets.QTextBrowser(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(710, 430, 391, 61))
        self.time.setStyleSheet("color: rgb(207, 255, 255);\n"
"background-color: rgb(255, 249, 240);\n"
"color: rgb(0, 0, 0);\n"
"border: 2px Solid Pink;\n"
"font: 75 italic 24pt \"Palatino Linotype\";")
        self.time.setObjectName("time")
        self.gif_bg = QtWidgets.QLabel(self.centralwidget)
        self.gif_bg.setGeometry(QtCore.QRect(10, 10, 1101, 621))
        self.gif_bg.setText("")
        self.gif_bg.setPixmap(QtGui.QPixmap(".\\../../../Downloads/matrix.gif"))
        self.gif_bg.setScaledContents(True)
        self.gif_bg.setObjectName("gif_bg")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 22, 681, 601))
        self.label.setText("")
        self.label.setObjectName("label")
        self.bg.raise_()
        self.gif_bg.raise_()
        self.frontier.raise_()
        self.time.raise_()
        self.start_button.raise_()
        self.close_button.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.close_button.setText(_translate("MainWindow", "CLOSE"))
        self.start_button.setText(_translate("MainWindow", "START"))
        self.time.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Palatino Linotype\'; font-size:24pt; font-weight:72; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Time:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
